/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package example1;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author sungureanu
 */
public class JFrame1 extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form JFrame1
     */
    public JFrame1() {
        initComponents();
        myInitComponents();
    }
    private void myInitComponents(){
    btnConvert = new JButton();
    label1 = new JLabel ("Enter Fahrenheit temp:");
    lblResult = new JLabel ();
    txtFahrenheit = new JTextField();
    txtFahrenheit.setPreferredSize(new Dimension(100, 25));
    panel1 = new JPanel(new FlowLayout());
    //add to panel
    panel1.add(label1);
    panel1.add(txtFahrenheit);
    
    lblResult = new JLabel();
    btnConvert = new JButton("Convert F to C");
    
    //register the action event with listener
    //this frame
    btnConvert.addActionListener(this);
    
    //add to this frame
    this.setLayout(new BorderLayout());
    this.add(panel1, BorderLayout.PAGE_START);
    this.add(lblResult, BorderLayout.CENTER);
    this.add(btnConvert, BorderLayout.PAGE_END);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
JButton btnConvert;
JLabel label1, lblResult;
JTextField txtFahrenheit;
JPanel panel1;

//this is Frames Listener
    @Override
    public void actionPerformed(ActionEvent ae) {
//check on the button that was clicked
if (btnConvert == (JButton)ae.getSource()) {
            //get temperature from text box
            double F = Double.parseDouble(txtFahrenheit.getText());
            //convert to celcius
            double C = (F-32)*5.0/9.0;
            //display
            lblResult.setText(String.valueOf(C));
        }
    } //go register this Listener in the frame with actionevent button
}
