/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package example1;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Box;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author sungureanu
 */
public class JFrame4 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame4
     */
    public JFrame4() {
        initComponents();
        myinitComponents();
    }

    private void myinitComponents(){
           Box verticalBox = Box.createVerticalBox();
       btn1 = new JButton("showMessageDialog");
        btn3= new JButton("showInputDialogWithOptions");
        btn2 = new JButton("showInputDialog");
        btn4 = new JButton("showOptionDialog");

        MyActionListener aListener = new MyActionListener();
        btn1.addActionListener(aListener);
        btn2.addActionListener(aListener);
        btn3.addActionListener(aListener);
        btn4.addActionListener(aListener);

               verticalBox.add(btn1);
        verticalBox.add(btn2);
        verticalBox.add(btn3);
        verticalBox.add(btn4);

        this.setLayout(new BorderLayout());
        this.add(verticalBox,BorderLayout.CENTER);
        
       this.pack();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame4().setVisible(true);
            }
        });
    }

    //define a private inner class to listen for Action events
    private class MyActionListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae) {
             if (btn1==(JButton)ae.getSource()) {
                //display a message dialog
                 JOptionPane.showMessageDialog(null, "This is a simple show dialog");
                 Icon icon = new ImageIcon("C:\\Users\\sungureanu\\Documents\\NetBeansProjects\\week-1\\ButtonActionEvent\\src\\ICons\\trash.gif");
                 JOptionPane.showMessageDialog(null, "This is a complete show dialog", 
                         "Message Dialog", 
                         JOptionPane.WARNING_MESSAGE, 
                         icon);
            }else if (btn2==(JButton)ae.getSource()) {
                //show input dialog
               String input =  JOptionPane.showInputDialog(null, "Enter your name: ", "new user");
               //display input
               JOptionPane.showMessageDialog(null, "Welcome " + input);
            }else if (btn3==(JButton)ae.getSource()) {
                //supply options
                 Icon icon = new ImageIcon("C:\\Users\\sungureanu\\Documents\\NetBeansProjects\\week-1\\ButtonActionEvent\\src\\ICons\\trash.gif");
               Object[] options = new Object[]{"C#", "JAVA", "C++", "PHP", "RUBY" };
                 Object selectedOption = JOptionPane.showInputDialog(null,
                        "Select your prefered language",
                        "input options dialog",
                        JOptionPane.NO_OPTION,
                        icon,
                        options,
                        "C#");
                 //Display user selection
                 JOptionPane.showMessageDialog(null, "Your prefered language is: " + selectedOption);
            }else if (btn4==(JButton)ae.getSource()) {
                /*
                public static int showOptionDialog(Component parentComponent,
                Object message,
                String title,
                int optionType,
                int messageType,
                Icon icon,
                Object[] options,
                Obkect initialValue)
                */
                //complete code to display a showOptionDialog
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
JButton btn1, btn2, btn3, btn4;

       
    }
