/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package example;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.NumberFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sungureanu
 */
public class JFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame1
     */
    public JFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnSerialize = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBtnDeserialize = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnSerialize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnSerialize.setText("Serialize Random Account");
        jBtnSerialize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSerializeActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jBtnDeserialize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnDeserialize.setText("Deserialize Account");
        jBtnDeserialize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeserializeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jBtnSerialize, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(jBtnDeserialize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnSerialize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnDeserialize)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSerializeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSerializeActionPerformed
        // TODO add your handling code here:
        //need two objects:
        // 1. ObjectOutputStream which defines the writeObject method to write an object to stream
        // 2. FileOutputStream to open the file or create it if it does not exist
        
        //create a random account object
        Random rand = new Random();
        int accountNumber = rand.nextInt(900000) + 123456;
        double balance = rand.nextInt(30000) + 1000;
        String[] types = new String[] {"Checking", "Savings", "CD"};
        String type = types[rand.nextInt(types.length)];
        String bank = "Chase";
        Account acc = new Account(accountNumber, balance, type, bank);
        
        ObjectOutputStream oos = null;
        try{
            oos = new ObjectOutputStream(new FileOutputStream("account.dat"));
            //serialize the object account
            oos.writeObject(acc);
            //optional: alert usser
            JOptionPane.showMessageDialog(this, "Random account was serialized");
        }catch(IOException ex){
        JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            if(oos!=null){
                try {
                    oos.close();
                } catch (IOException ex) {
                
                }
            }
        }
    }//GEN-LAST:event_jBtnSerializeActionPerformed

    private void jBtnDeserializeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeserializeActionPerformed
        // TODO add your handling code here:
        //use object InputStream (reads it) and FileInputStream (opens file)
        ObjectInputStream ois = null;
          
        try{
           ois = new ObjectInputStream(new FileInputStream("account.dat"));
           //deserialize the account object
           Account a = (Account)ois.readObject();
            //optional: alert usser
            JOptionPane.showMessageDialog(this, "Random account was deserialized");
           NumberFormat nf = NumberFormat.getCurrencyInstance();
           jTextArea1.setText("account number: " + a.getAccountNumber() + "\n" +
                   "balance: " + nf.format(a.getBalance())+ "\n" + 
                   "account type: " + a.getType() + "\n" + 
                   "bank name: " + a.getBank());
        }catch(IOException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }catch(ClassNotFoundException cex){
            JOptionPane.showMessageDialog(this, cex.getMessage());
        }finally{
            if(ois!=null){
                try {
                    ois.close();
                } catch (IOException ex) {
                
                }
            }
        }     
        
    }//GEN-LAST:event_jBtnDeserializeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDeserialize;
    private javax.swing.JButton jBtnSerialize;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
//Add to this project
//add a button that creates at least 12 random accounts, save them to an
//array list, then serialize the list
//add another button that deserializes the list and display all the accounts