/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examle_1;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.net.URL;
//import javax.swing.BorderFactory;
//import javax.swing.BoxLayout;
//import javax.swing.ButtonGroup;
//import javax.swing.JCheckBox;
//import javax.swing.JLabel;
//import javax.swing.JPanel;
//import javax.swing.JRadioButton;
//import javax.swing.JTextField;
import javax.swing.*;
/**
 *
 * @author HOMER
 */
public class JFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame3
     */
    public JFrame3() {
        initComponents();
        myInitComponents();
    }
    private void myInitComponents(){
    checkbox1 = new JCheckBox("Check Box 1");
    checkbox2 = new JCheckBox("Check Box 2");
    checkbox3 = new JCheckBox("Check Box 3");
            
    radbtn1 = new JRadioButton("Radio Button 1");
    radbtn2 = new JRadioButton("Radio Button 2");
    radbtn3 = new JRadioButton("Radio Button 3");
       
    ButtonGroup group = new ButtonGroup();
    group.add(radbtn1);
    group.add(radbtn2);
    group.add(radbtn3);
    
    
    lbl1 = new JLabel("LABEL");
   
    //center lamble+image
    lblpicture = new JLabel(new ImageIcon(getClass().getResource("/img/image.jpg")));
   
    
    txtField1 = new JTextField("field 1");
    txtField2 = new JTextField("field 2");
    
    //left panel
    panelLaneStart = new JPanel();
    panelLaneStart.setLayout(new BoxLayout(panelLaneStart, BoxLayout.PAGE_AXIS));
    panelLaneStart.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));
    panelLaneStart.add(checkbox1);
    panelLaneStart.add(checkbox2);
    panelLaneStart.add(checkbox3);
    
    //right panel
    panelLaneEnd = new JPanel();
    panelLaneEnd.setLayout(new BoxLayout(panelLaneEnd, BoxLayout.PAGE_AXIS));
    panelLaneEnd.setBorder(BorderFactory.createEmptyBorder(10,10,10,12));
    panelLaneEnd.add(radbtn1);
    panelLaneEnd.add(radbtn2);
    panelLaneEnd.add(radbtn3);
    
    //top panel
    panelPageStart = new JPanel();
    panelPageStart.setLayout(new GridLayout());
    panelPageStart.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));
    panelPageStart.add(lbl1);
    panelPageStart.add(txtField1);
    
    //add the frame
    this.setLayout(new BorderLayout());
    this.add(panelPageStart, BorderLayout.PAGE_START);
    this.add(panelLaneStart, BorderLayout.LINE_START);
    this.add(panelLaneEnd, BorderLayout.LINE_END);
    this.add(txtField2, BorderLayout.PAGE_END);
    this.add(lblpicture, BorderLayout.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame3().setVisible(true);
            }
        });
    }
    
JCheckBox checkbox1, checkbox2, checkbox3;
JRadioButton radbtn1, radbtn2, radbtn3;
JLabel lbl1, lblpicture;
JTextField txtField1, txtField2;
JPanel panelLaneStart, panelLaneEnd, panelPageStart;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
//Exercise:
//Add JFrame3
//Set its layout to BorderLayout
//add 3 JCheckBoxes to its LINE_START
//add 3 JRadioButtons to its LINE_END
//add a JLabel and a textbox (JTextField) to its PAGE_START
//add a JTextField to tis PAGE_END